{{- $SYSTEM_SC_NAME := include "SYSTEM_SC_NAME" . -}} 
{{- $COURSE_SC_NAME := include "COURSE_SC_NAME" . -}}


{{ range .Values.namespace_suffix }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.common.namespace_prefix }}-{{ . }}
  {{ if ne . "system" }}
  labels:
    instance: {{ $.Values.common.namespace_prefix }}
  {{ end }}
---
{{ end }}

---

#https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.common.namespace_prefix}}-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---

{{ if ne $SYSTEM_SC_NAME $COURSE_SC_NAME }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.common.namespace_prefix }}-course-provisioner

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.common.namespace_prefix}}-course-provisioner
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

---

# https://blog.frognew.com/2018/09/using-helm-manage-tls-secret.html
{{ range .Values.namespace_suffix }}
apiVersion: v1
kind: Secret
metadata:
  name: nchc-tls-secret
  namespace: {{ $.Values.common.namespace_prefix }}-{{ . }}
type: kubernetes.io/tls
data:
  {{ if eq $.Values.tls_secret.from_file true }}
  tls.crt: {{ $.Files.Get $.Values.tls_secret.certificate_file | b64enc }}
  tls.key: {{ $.Files.Get $.Values.tls_secret.key_file | b64enc }}
  {{ else }}
  tls.crt: {{ $.Values.tls_secret.certificate | b64enc }}
  tls.key: {{ $.Values.tls_secret.key | b64enc }}
  {{ end }}
---
{{ end }}