{{- $SYSTEM_SC_NAME := include "SYSTEM_SC_NAME" . -}} 
{{- $COURSE_SC_NAME := include "COURSE_SC_NAME" . -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.common.namespace_prefix }}-system

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.common.namespace_prefix }}-public
  labels:
    instance: {{ .Values.common.namespace_prefix }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.common.namespace_prefix }}-teacher
  labels:
    instance: {{ .Values.common.namespace_prefix }}

---

#https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.common.namespace_prefix}}-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---

{{- if ne $SYSTEM_SC_NAME $COURSE_SC_NAME -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.common.namespace_prefix }}-course-provisioner

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.common.namespace_prefix}}-course-provisioner
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

---

{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: nchc-tls-secret
  namespace: {{ .name }}-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
{{- end }}